apiVersion: v1
kind: Service
metadata:
  name: master-cluster-ip
spec:
  selector:
    app: master
  ports:
    - protocol: TCP
      port: {{ .Values.master.grpc_port }}
      targetPort: {{ .Values.master.grpc_port }}
  clusterIP: {{ .Values.master.address }}
