#!/bin/bash

# Set the desired Boost version
BOOST_VERSION="1.76.0"
BOOST_DIR="$HOME/boost"

# Replace dots with underscores for the directory name
BOOST_VERSION_UNDERSCORE=${BOOST_VERSION//./_}

# Download URL
DOWNLOAD_URL="https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION_UNDERSCORE}.tar.gz"

# Check if Boost is already installed
if [ -d "$BOOST_DIR" ]; then
    echo "Boost is already installed at ${BOOST_DIR}."
    exit 0
fi

# Download Boost
echo "Downloading Boost ${BOOST_VERSION}..."
wget ${DOWNLOAD_URL} -O boost_${BOOST_VERSION_UNDERSCORE}.tar.gz

# Extract
echo "Extracting Boost..."
tar -xzf boost_${BOOST_VERSION_UNDERSCORE}.tar.gz
cd boost_${BOOST_VERSION_UNDERSCORE}

# Bootstrap
echo "Bootstrapping Boost..."
./bootstrap.sh

# Build and install
echo "Building and installing Boost in ${BOOST_DIR}..."
./b2 install --prefix=$HOME/boost link=static cxxflags="-fPIC" linkflags="-fPIC"

echo "Boost installation completed."

cd ..
rm -rf boost_${BOOST_VERSION_UNDERSCORE}
rm -rf boost_${BOOST_VERSION_UNDERSCORE}.tar.gz
