// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master_service.proto

#include "master_service.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
        template <typename>
PROTOBUF_CONSTEXPR RegisterWorkerRequest::RegisterWorkerRequest(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.ip_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.port_)*/ 0,
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct RegisterWorkerRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RegisterWorkerRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RegisterWorkerRequestDefaultTypeInternal() {}
  union {
    RegisterWorkerRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RegisterWorkerRequestDefaultTypeInternal _RegisterWorkerRequest_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR RegisterWorkerReply::RegisterWorkerReply(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.ok_)*/ false,
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct RegisterWorkerReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RegisterWorkerReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RegisterWorkerReplyDefaultTypeInternal() {}
  union {
    RegisterWorkerReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RegisterWorkerReplyDefaultTypeInternal _RegisterWorkerReply_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR RegisterJobRequest::RegisterJobRequest(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.path_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.mapper_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.reducer_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct RegisterJobRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RegisterJobRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RegisterJobRequestDefaultTypeInternal() {}
  union {
    RegisterJobRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RegisterJobRequestDefaultTypeInternal _RegisterJobRequest_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR RegisterJobReply::RegisterJobReply(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.ok_)*/ false,
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct RegisterJobReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RegisterJobReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RegisterJobReplyDefaultTypeInternal() {}
  union {
    RegisterJobReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RegisterJobReplyDefaultTypeInternal _RegisterJobReply_default_instance_;
static ::_pb::Metadata file_level_metadata_master_5fservice_2eproto[4];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_master_5fservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_master_5fservice_2eproto = nullptr;
const ::uint32_t TableStruct_master_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::RegisterWorkerRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::RegisterWorkerRequest, _impl_.ip_),
    PROTOBUF_FIELD_OFFSET(::RegisterWorkerRequest, _impl_.port_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::RegisterWorkerReply, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::RegisterWorkerReply, _impl_.ok_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::RegisterJobRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::RegisterJobRequest, _impl_.path_),
    PROTOBUF_FIELD_OFFSET(::RegisterJobRequest, _impl_.mapper_),
    PROTOBUF_FIELD_OFFSET(::RegisterJobRequest, _impl_.reducer_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::RegisterJobReply, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::RegisterJobReply, _impl_.ok_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::RegisterWorkerRequest)},
        {10, -1, -1, sizeof(::RegisterWorkerReply)},
        {19, -1, -1, sizeof(::RegisterJobRequest)},
        {30, -1, -1, sizeof(::RegisterJobReply)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_RegisterWorkerRequest_default_instance_._instance,
    &::_RegisterWorkerReply_default_instance_._instance,
    &::_RegisterJobRequest_default_instance_._instance,
    &::_RegisterJobReply_default_instance_._instance,
};
const char descriptor_table_protodef_master_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\024master_service.proto\"1\n\025RegisterWorker"
    "Request\022\n\n\002ip\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\"!\n\023Reg"
    "isterWorkerReply\022\n\n\002ok\030\001 \001(\010\"C\n\022Register"
    "JobRequest\022\014\n\004path\030\001 \001(\t\022\016\n\006mapper\030\002 \001(\t"
    "\022\017\n\007reducer\030\003 \001(\t\"\036\n\020RegisterJobReply\022\n\n"
    "\002ok\030\001 \001(\0102\212\001\n\rMasterService\022@\n\016RegisterW"
    "orker\022\026.RegisterWorkerRequest\032\024.Register"
    "WorkerReply\"\000\0227\n\013RegisterJob\022\023.RegisterJ"
    "obRequest\032\021.RegisterJobReply\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_master_5fservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_master_5fservice_2eproto = {
    false,
    false,
    358,
    descriptor_table_protodef_master_5fservice_2eproto,
    "master_service.proto",
    &descriptor_table_master_5fservice_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_master_5fservice_2eproto::offsets,
    file_level_metadata_master_5fservice_2eproto,
    file_level_enum_descriptors_master_5fservice_2eproto,
    file_level_service_descriptors_master_5fservice_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_master_5fservice_2eproto_getter() {
  return &descriptor_table_master_5fservice_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_master_5fservice_2eproto(&descriptor_table_master_5fservice_2eproto);
// ===================================================================

class RegisterWorkerRequest::_Internal {
 public:
};

RegisterWorkerRequest::RegisterWorkerRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RegisterWorkerRequest)
}
RegisterWorkerRequest::RegisterWorkerRequest(const RegisterWorkerRequest& from) : ::google::protobuf::Message() {
  RegisterWorkerRequest* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ip_){},
      decltype(_impl_.port_){},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  _impl_.ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.ip_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_ip().empty()) {
    _this->_impl_.ip_.Set(from._internal_ip(), _this->GetArenaForAllocation());
  }
  _this->_impl_.port_ = from._impl_.port_;

  // @@protoc_insertion_point(copy_constructor:RegisterWorkerRequest)
}
inline void RegisterWorkerRequest::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.ip_){},
      decltype(_impl_.port_){0},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _impl_.ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.ip_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}
RegisterWorkerRequest::~RegisterWorkerRequest() {
  // @@protoc_insertion_point(destructor:RegisterWorkerRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RegisterWorkerRequest::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.ip_.Destroy();
}
void RegisterWorkerRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void RegisterWorkerRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:RegisterWorkerRequest)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ip_.ClearToEmpty();
  _impl_.port_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RegisterWorkerRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 32, 2> RegisterWorkerRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RegisterWorkerRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 port = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RegisterWorkerRequest, _impl_.port_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(RegisterWorkerRequest, _impl_.port_)}},
    // string ip = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RegisterWorkerRequest, _impl_.ip_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string ip = 1;
    {PROTOBUF_FIELD_OFFSET(RegisterWorkerRequest, _impl_.ip_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 port = 2;
    {PROTOBUF_FIELD_OFFSET(RegisterWorkerRequest, _impl_.port_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\25\2\0\0\0\0\0\0"
    "RegisterWorkerRequest"
    "ip"
  }},
};

::uint8_t* RegisterWorkerRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RegisterWorkerRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string ip = 1;
  if (!this->_internal_ip().empty()) {
    const std::string& _s = this->_internal_ip();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "RegisterWorkerRequest.ip");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // int32 port = 2;
  if (this->_internal_port() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_port(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RegisterWorkerRequest)
  return target;
}

::size_t RegisterWorkerRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RegisterWorkerRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string ip = 1;
  if (!this->_internal_ip().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_ip());
  }

  // int32 port = 2;
  if (this->_internal_port() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_port());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RegisterWorkerRequest::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    RegisterWorkerRequest::MergeImpl
};
const ::google::protobuf::Message::ClassData*RegisterWorkerRequest::GetClassData() const { return &_class_data_; }


void RegisterWorkerRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RegisterWorkerRequest*>(&to_msg);
  auto& from = static_cast<const RegisterWorkerRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RegisterWorkerRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_ip().empty()) {
    _this->_internal_set_ip(from._internal_ip());
  }
  if (from._internal_port() != 0) {
    _this->_internal_set_port(from._internal_port());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RegisterWorkerRequest::CopyFrom(const RegisterWorkerRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RegisterWorkerRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RegisterWorkerRequest::IsInitialized() const {
  return true;
}

void RegisterWorkerRequest::InternalSwap(RegisterWorkerRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ip_, lhs_arena,
                                       &other->_impl_.ip_, rhs_arena);
        swap(_impl_.port_, other->_impl_.port_);
}

::google::protobuf::Metadata RegisterWorkerRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_master_5fservice_2eproto_getter, &descriptor_table_master_5fservice_2eproto_once,
      file_level_metadata_master_5fservice_2eproto[0]);
}
// ===================================================================

class RegisterWorkerReply::_Internal {
 public:
};

RegisterWorkerReply::RegisterWorkerReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RegisterWorkerReply)
}
RegisterWorkerReply::RegisterWorkerReply(const RegisterWorkerReply& from)
    : ::google::protobuf::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:RegisterWorkerReply)
}
inline void RegisterWorkerReply::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.ok_){false},
      /*decltype(_impl_._cached_size_)*/ {},
  };
}
RegisterWorkerReply::~RegisterWorkerReply() {
  // @@protoc_insertion_point(destructor:RegisterWorkerReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RegisterWorkerReply::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}
void RegisterWorkerReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void RegisterWorkerReply::Clear() {
// @@protoc_insertion_point(message_clear_start:RegisterWorkerReply)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ok_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RegisterWorkerReply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> RegisterWorkerReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RegisterWorkerReply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bool ok = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(RegisterWorkerReply, _impl_.ok_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RegisterWorkerReply, _impl_.ok_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool ok = 1;
    {PROTOBUF_FIELD_OFFSET(RegisterWorkerReply, _impl_.ok_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* RegisterWorkerReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RegisterWorkerReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool ok = 1;
  if (this->_internal_ok() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_ok(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RegisterWorkerReply)
  return target;
}

::size_t RegisterWorkerReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RegisterWorkerReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool ok = 1;
  if (this->_internal_ok() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RegisterWorkerReply::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    RegisterWorkerReply::MergeImpl
};
const ::google::protobuf::Message::ClassData*RegisterWorkerReply::GetClassData() const { return &_class_data_; }


void RegisterWorkerReply::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RegisterWorkerReply*>(&to_msg);
  auto& from = static_cast<const RegisterWorkerReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RegisterWorkerReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_ok() != 0) {
    _this->_internal_set_ok(from._internal_ok());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RegisterWorkerReply::CopyFrom(const RegisterWorkerReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RegisterWorkerReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RegisterWorkerReply::IsInitialized() const {
  return true;
}

void RegisterWorkerReply::InternalSwap(RegisterWorkerReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.ok_, other->_impl_.ok_);
}

::google::protobuf::Metadata RegisterWorkerReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_master_5fservice_2eproto_getter, &descriptor_table_master_5fservice_2eproto_once,
      file_level_metadata_master_5fservice_2eproto[1]);
}
// ===================================================================

class RegisterJobRequest::_Internal {
 public:
};

RegisterJobRequest::RegisterJobRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RegisterJobRequest)
}
RegisterJobRequest::RegisterJobRequest(const RegisterJobRequest& from) : ::google::protobuf::Message() {
  RegisterJobRequest* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.path_){},
      decltype(_impl_.mapper_){},
      decltype(_impl_.reducer_){},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  _impl_.path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.path_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_path().empty()) {
    _this->_impl_.path_.Set(from._internal_path(), _this->GetArenaForAllocation());
  }
  _impl_.mapper_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.mapper_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_mapper().empty()) {
    _this->_impl_.mapper_.Set(from._internal_mapper(), _this->GetArenaForAllocation());
  }
  _impl_.reducer_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.reducer_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_reducer().empty()) {
    _this->_impl_.reducer_.Set(from._internal_reducer(), _this->GetArenaForAllocation());
  }

  // @@protoc_insertion_point(copy_constructor:RegisterJobRequest)
}
inline void RegisterJobRequest::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.path_){},
      decltype(_impl_.mapper_){},
      decltype(_impl_.reducer_){},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _impl_.path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.path_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.mapper_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.mapper_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.reducer_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.reducer_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}
RegisterJobRequest::~RegisterJobRequest() {
  // @@protoc_insertion_point(destructor:RegisterJobRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RegisterJobRequest::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.path_.Destroy();
  _impl_.mapper_.Destroy();
  _impl_.reducer_.Destroy();
}
void RegisterJobRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void RegisterJobRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:RegisterJobRequest)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.path_.ClearToEmpty();
  _impl_.mapper_.ClearToEmpty();
  _impl_.reducer_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RegisterJobRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 44, 2> RegisterJobRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RegisterJobRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string path = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RegisterJobRequest, _impl_.path_)}},
    // string mapper = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(RegisterJobRequest, _impl_.mapper_)}},
    // string reducer = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(RegisterJobRequest, _impl_.reducer_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string path = 1;
    {PROTOBUF_FIELD_OFFSET(RegisterJobRequest, _impl_.path_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string mapper = 2;
    {PROTOBUF_FIELD_OFFSET(RegisterJobRequest, _impl_.mapper_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string reducer = 3;
    {PROTOBUF_FIELD_OFFSET(RegisterJobRequest, _impl_.reducer_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\4\6\7\0\0\0\0"
    "RegisterJobRequest"
    "path"
    "mapper"
    "reducer"
  }},
};

::uint8_t* RegisterJobRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RegisterJobRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string path = 1;
  if (!this->_internal_path().empty()) {
    const std::string& _s = this->_internal_path();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "RegisterJobRequest.path");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string mapper = 2;
  if (!this->_internal_mapper().empty()) {
    const std::string& _s = this->_internal_mapper();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "RegisterJobRequest.mapper");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string reducer = 3;
  if (!this->_internal_reducer().empty()) {
    const std::string& _s = this->_internal_reducer();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "RegisterJobRequest.reducer");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RegisterJobRequest)
  return target;
}

::size_t RegisterJobRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RegisterJobRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string path = 1;
  if (!this->_internal_path().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_path());
  }

  // string mapper = 2;
  if (!this->_internal_mapper().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_mapper());
  }

  // string reducer = 3;
  if (!this->_internal_reducer().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_reducer());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RegisterJobRequest::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    RegisterJobRequest::MergeImpl
};
const ::google::protobuf::Message::ClassData*RegisterJobRequest::GetClassData() const { return &_class_data_; }


void RegisterJobRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RegisterJobRequest*>(&to_msg);
  auto& from = static_cast<const RegisterJobRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RegisterJobRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_path().empty()) {
    _this->_internal_set_path(from._internal_path());
  }
  if (!from._internal_mapper().empty()) {
    _this->_internal_set_mapper(from._internal_mapper());
  }
  if (!from._internal_reducer().empty()) {
    _this->_internal_set_reducer(from._internal_reducer());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RegisterJobRequest::CopyFrom(const RegisterJobRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RegisterJobRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RegisterJobRequest::IsInitialized() const {
  return true;
}

void RegisterJobRequest::InternalSwap(RegisterJobRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.path_, lhs_arena,
                                       &other->_impl_.path_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.mapper_, lhs_arena,
                                       &other->_impl_.mapper_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.reducer_, lhs_arena,
                                       &other->_impl_.reducer_, rhs_arena);
}

::google::protobuf::Metadata RegisterJobRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_master_5fservice_2eproto_getter, &descriptor_table_master_5fservice_2eproto_once,
      file_level_metadata_master_5fservice_2eproto[2]);
}
// ===================================================================

class RegisterJobReply::_Internal {
 public:
};

RegisterJobReply::RegisterJobReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RegisterJobReply)
}
RegisterJobReply::RegisterJobReply(const RegisterJobReply& from)
    : ::google::protobuf::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:RegisterJobReply)
}
inline void RegisterJobReply::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.ok_){false},
      /*decltype(_impl_._cached_size_)*/ {},
  };
}
RegisterJobReply::~RegisterJobReply() {
  // @@protoc_insertion_point(destructor:RegisterJobReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RegisterJobReply::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}
void RegisterJobReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void RegisterJobReply::Clear() {
// @@protoc_insertion_point(message_clear_start:RegisterJobReply)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ok_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RegisterJobReply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> RegisterJobReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RegisterJobReply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bool ok = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(RegisterJobReply, _impl_.ok_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RegisterJobReply, _impl_.ok_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool ok = 1;
    {PROTOBUF_FIELD_OFFSET(RegisterJobReply, _impl_.ok_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* RegisterJobReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RegisterJobReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool ok = 1;
  if (this->_internal_ok() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_ok(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RegisterJobReply)
  return target;
}

::size_t RegisterJobReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RegisterJobReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool ok = 1;
  if (this->_internal_ok() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RegisterJobReply::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    RegisterJobReply::MergeImpl
};
const ::google::protobuf::Message::ClassData*RegisterJobReply::GetClassData() const { return &_class_data_; }


void RegisterJobReply::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RegisterJobReply*>(&to_msg);
  auto& from = static_cast<const RegisterJobReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RegisterJobReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_ok() != 0) {
    _this->_internal_set_ok(from._internal_ok());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RegisterJobReply::CopyFrom(const RegisterJobReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RegisterJobReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RegisterJobReply::IsInitialized() const {
  return true;
}

void RegisterJobReply::InternalSwap(RegisterJobReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.ok_, other->_impl_.ok_);
}

::google::protobuf::Metadata RegisterJobReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_master_5fservice_2eproto_getter, &descriptor_table_master_5fservice_2eproto_once,
      file_level_metadata_master_5fservice_2eproto[3]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
