// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: worker_service.proto

#include "worker_service.pb.h"
#include "worker_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* WorkerService_method_names[] = {
  "/WorkerService/AssignWork",
};

std::unique_ptr< WorkerService::Stub> WorkerService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< WorkerService::Stub> stub(new WorkerService::Stub(channel, options));
  return stub;
}

WorkerService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_AssignWork_(WorkerService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status WorkerService::Stub::AssignWork(::grpc::ClientContext* context, const ::AssignWorkRequest& request, ::AssignWorkReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AssignWorkRequest, ::AssignWorkReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AssignWork_, context, request, response);
}

void WorkerService::Stub::async::AssignWork(::grpc::ClientContext* context, const ::AssignWorkRequest* request, ::AssignWorkReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AssignWorkRequest, ::AssignWorkReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AssignWork_, context, request, response, std::move(f));
}

void WorkerService::Stub::async::AssignWork(::grpc::ClientContext* context, const ::AssignWorkRequest* request, ::AssignWorkReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AssignWork_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AssignWorkReply>* WorkerService::Stub::PrepareAsyncAssignWorkRaw(::grpc::ClientContext* context, const ::AssignWorkRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AssignWorkReply, ::AssignWorkRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AssignWork_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AssignWorkReply>* WorkerService::Stub::AsyncAssignWorkRaw(::grpc::ClientContext* context, const ::AssignWorkRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAssignWorkRaw(context, request, cq);
  result->StartCall();
  return result;
}

WorkerService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WorkerService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WorkerService::Service, ::AssignWorkRequest, ::AssignWorkReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WorkerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AssignWorkRequest* req,
             ::AssignWorkReply* resp) {
               return service->AssignWork(ctx, req, resp);
             }, this)));
}

WorkerService::Service::~Service() {
}

::grpc::Status WorkerService::Service::AssignWork(::grpc::ServerContext* context, const ::AssignWorkRequest* request, ::AssignWorkReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


