// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: worker_service.proto
#ifndef GRPC_worker_5fservice_2eproto__INCLUDED
#define GRPC_worker_5fservice_2eproto__INCLUDED

#include "worker_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

class WorkerService final {
 public:
  static constexpr char const* service_full_name() {
    return "WorkerService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status AssignWork(::grpc::ClientContext* context, const ::AssignWorkRequest& request, ::AssignWorkReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AssignWorkReply>> AsyncAssignWork(::grpc::ClientContext* context, const ::AssignWorkRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AssignWorkReply>>(AsyncAssignWorkRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AssignWorkReply>> PrepareAsyncAssignWork(::grpc::ClientContext* context, const ::AssignWorkRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AssignWorkReply>>(PrepareAsyncAssignWorkRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void AssignWork(::grpc::ClientContext* context, const ::AssignWorkRequest* request, ::AssignWorkReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AssignWork(::grpc::ClientContext* context, const ::AssignWorkRequest* request, ::AssignWorkReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AssignWorkReply>* AsyncAssignWorkRaw(::grpc::ClientContext* context, const ::AssignWorkRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AssignWorkReply>* PrepareAsyncAssignWorkRaw(::grpc::ClientContext* context, const ::AssignWorkRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AssignWork(::grpc::ClientContext* context, const ::AssignWorkRequest& request, ::AssignWorkReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AssignWorkReply>> AsyncAssignWork(::grpc::ClientContext* context, const ::AssignWorkRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AssignWorkReply>>(AsyncAssignWorkRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AssignWorkReply>> PrepareAsyncAssignWork(::grpc::ClientContext* context, const ::AssignWorkRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AssignWorkReply>>(PrepareAsyncAssignWorkRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AssignWork(::grpc::ClientContext* context, const ::AssignWorkRequest* request, ::AssignWorkReply* response, std::function<void(::grpc::Status)>) override;
      void AssignWork(::grpc::ClientContext* context, const ::AssignWorkRequest* request, ::AssignWorkReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::AssignWorkReply>* AsyncAssignWorkRaw(::grpc::ClientContext* context, const ::AssignWorkRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::AssignWorkReply>* PrepareAsyncAssignWorkRaw(::grpc::ClientContext* context, const ::AssignWorkRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AssignWork_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status AssignWork(::grpc::ServerContext* context, const ::AssignWorkRequest* request, ::AssignWorkReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AssignWork : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AssignWork() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AssignWork() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AssignWork(::grpc::ServerContext* /*context*/, const ::AssignWorkRequest* /*request*/, ::AssignWorkReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAssignWork(::grpc::ServerContext* context, ::AssignWorkRequest* request, ::grpc::ServerAsyncResponseWriter< ::AssignWorkReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AssignWork<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AssignWork : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AssignWork() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::AssignWorkRequest, ::AssignWorkReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::AssignWorkRequest* request, ::AssignWorkReply* response) { return this->AssignWork(context, request, response); }));}
    void SetMessageAllocatorFor_AssignWork(
        ::grpc::MessageAllocator< ::AssignWorkRequest, ::AssignWorkReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::AssignWorkRequest, ::AssignWorkReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AssignWork() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AssignWork(::grpc::ServerContext* /*context*/, const ::AssignWorkRequest* /*request*/, ::AssignWorkReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AssignWork(
      ::grpc::CallbackServerContext* /*context*/, const ::AssignWorkRequest* /*request*/, ::AssignWorkReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AssignWork<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AssignWork : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AssignWork() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AssignWork() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AssignWork(::grpc::ServerContext* /*context*/, const ::AssignWorkRequest* /*request*/, ::AssignWorkReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AssignWork : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AssignWork() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AssignWork() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AssignWork(::grpc::ServerContext* /*context*/, const ::AssignWorkRequest* /*request*/, ::AssignWorkReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAssignWork(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AssignWork : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AssignWork() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AssignWork(context, request, response); }));
    }
    ~WithRawCallbackMethod_AssignWork() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AssignWork(::grpc::ServerContext* /*context*/, const ::AssignWorkRequest* /*request*/, ::AssignWorkReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AssignWork(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AssignWork : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AssignWork() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::AssignWorkRequest, ::AssignWorkReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::AssignWorkRequest, ::AssignWorkReply>* streamer) {
                       return this->StreamedAssignWork(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AssignWork() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AssignWork(::grpc::ServerContext* /*context*/, const ::AssignWorkRequest* /*request*/, ::AssignWorkReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAssignWork(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::AssignWorkRequest,::AssignWorkReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AssignWork<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AssignWork<Service > StreamedService;
};


#endif  // GRPC_worker_5fservice_2eproto__INCLUDED
