// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: master_service.proto
#ifndef GRPC_master_5fservice_2eproto__INCLUDED
#define GRPC_master_5fservice_2eproto__INCLUDED

#include "master_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

class MasterService final {
 public:
  static constexpr char const* service_full_name() {
    return "MasterService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RegisterWorker(::grpc::ClientContext* context, const ::RegisterWorkerRequest& request, ::RegisterWorkerReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RegisterWorkerReply>> AsyncRegisterWorker(::grpc::ClientContext* context, const ::RegisterWorkerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RegisterWorkerReply>>(AsyncRegisterWorkerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RegisterWorkerReply>> PrepareAsyncRegisterWorker(::grpc::ClientContext* context, const ::RegisterWorkerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RegisterWorkerReply>>(PrepareAsyncRegisterWorkerRaw(context, request, cq));
    }
    virtual ::grpc::Status RegisterJob(::grpc::ClientContext* context, const ::RegisterJobRequest& request, ::RegisterJobReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RegisterJobReply>> AsyncRegisterJob(::grpc::ClientContext* context, const ::RegisterJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RegisterJobReply>>(AsyncRegisterJobRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RegisterJobReply>> PrepareAsyncRegisterJob(::grpc::ClientContext* context, const ::RegisterJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RegisterJobReply>>(PrepareAsyncRegisterJobRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RegisterWorker(::grpc::ClientContext* context, const ::RegisterWorkerRequest* request, ::RegisterWorkerReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RegisterWorker(::grpc::ClientContext* context, const ::RegisterWorkerRequest* request, ::RegisterWorkerReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void RegisterJob(::grpc::ClientContext* context, const ::RegisterJobRequest* request, ::RegisterJobReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RegisterJob(::grpc::ClientContext* context, const ::RegisterJobRequest* request, ::RegisterJobReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RegisterWorkerReply>* AsyncRegisterWorkerRaw(::grpc::ClientContext* context, const ::RegisterWorkerRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RegisterWorkerReply>* PrepareAsyncRegisterWorkerRaw(::grpc::ClientContext* context, const ::RegisterWorkerRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RegisterJobReply>* AsyncRegisterJobRaw(::grpc::ClientContext* context, const ::RegisterJobRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RegisterJobReply>* PrepareAsyncRegisterJobRaw(::grpc::ClientContext* context, const ::RegisterJobRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RegisterWorker(::grpc::ClientContext* context, const ::RegisterWorkerRequest& request, ::RegisterWorkerReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RegisterWorkerReply>> AsyncRegisterWorker(::grpc::ClientContext* context, const ::RegisterWorkerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RegisterWorkerReply>>(AsyncRegisterWorkerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RegisterWorkerReply>> PrepareAsyncRegisterWorker(::grpc::ClientContext* context, const ::RegisterWorkerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RegisterWorkerReply>>(PrepareAsyncRegisterWorkerRaw(context, request, cq));
    }
    ::grpc::Status RegisterJob(::grpc::ClientContext* context, const ::RegisterJobRequest& request, ::RegisterJobReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RegisterJobReply>> AsyncRegisterJob(::grpc::ClientContext* context, const ::RegisterJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RegisterJobReply>>(AsyncRegisterJobRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RegisterJobReply>> PrepareAsyncRegisterJob(::grpc::ClientContext* context, const ::RegisterJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RegisterJobReply>>(PrepareAsyncRegisterJobRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RegisterWorker(::grpc::ClientContext* context, const ::RegisterWorkerRequest* request, ::RegisterWorkerReply* response, std::function<void(::grpc::Status)>) override;
      void RegisterWorker(::grpc::ClientContext* context, const ::RegisterWorkerRequest* request, ::RegisterWorkerReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RegisterJob(::grpc::ClientContext* context, const ::RegisterJobRequest* request, ::RegisterJobReply* response, std::function<void(::grpc::Status)>) override;
      void RegisterJob(::grpc::ClientContext* context, const ::RegisterJobRequest* request, ::RegisterJobReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::RegisterWorkerReply>* AsyncRegisterWorkerRaw(::grpc::ClientContext* context, const ::RegisterWorkerRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RegisterWorkerReply>* PrepareAsyncRegisterWorkerRaw(::grpc::ClientContext* context, const ::RegisterWorkerRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RegisterJobReply>* AsyncRegisterJobRaw(::grpc::ClientContext* context, const ::RegisterJobRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RegisterJobReply>* PrepareAsyncRegisterJobRaw(::grpc::ClientContext* context, const ::RegisterJobRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RegisterWorker_;
    const ::grpc::internal::RpcMethod rpcmethod_RegisterJob_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RegisterWorker(::grpc::ServerContext* context, const ::RegisterWorkerRequest* request, ::RegisterWorkerReply* response);
    virtual ::grpc::Status RegisterJob(::grpc::ServerContext* context, const ::RegisterJobRequest* request, ::RegisterJobReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RegisterWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RegisterWorker() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RegisterWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterWorker(::grpc::ServerContext* /*context*/, const ::RegisterWorkerRequest* /*request*/, ::RegisterWorkerReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterWorker(::grpc::ServerContext* context, ::RegisterWorkerRequest* request, ::grpc::ServerAsyncResponseWriter< ::RegisterWorkerReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RegisterJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RegisterJob() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RegisterJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterJob(::grpc::ServerContext* /*context*/, const ::RegisterJobRequest* /*request*/, ::RegisterJobReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterJob(::grpc::ServerContext* context, ::RegisterJobRequest* request, ::grpc::ServerAsyncResponseWriter< ::RegisterJobReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RegisterWorker<WithAsyncMethod_RegisterJob<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RegisterWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RegisterWorker() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::RegisterWorkerRequest, ::RegisterWorkerReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::RegisterWorkerRequest* request, ::RegisterWorkerReply* response) { return this->RegisterWorker(context, request, response); }));}
    void SetMessageAllocatorFor_RegisterWorker(
        ::grpc::MessageAllocator< ::RegisterWorkerRequest, ::RegisterWorkerReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::RegisterWorkerRequest, ::RegisterWorkerReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RegisterWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterWorker(::grpc::ServerContext* /*context*/, const ::RegisterWorkerRequest* /*request*/, ::RegisterWorkerReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterWorker(
      ::grpc::CallbackServerContext* /*context*/, const ::RegisterWorkerRequest* /*request*/, ::RegisterWorkerReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RegisterJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RegisterJob() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::RegisterJobRequest, ::RegisterJobReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::RegisterJobRequest* request, ::RegisterJobReply* response) { return this->RegisterJob(context, request, response); }));}
    void SetMessageAllocatorFor_RegisterJob(
        ::grpc::MessageAllocator< ::RegisterJobRequest, ::RegisterJobReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::RegisterJobRequest, ::RegisterJobReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RegisterJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterJob(::grpc::ServerContext* /*context*/, const ::RegisterJobRequest* /*request*/, ::RegisterJobReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterJob(
      ::grpc::CallbackServerContext* /*context*/, const ::RegisterJobRequest* /*request*/, ::RegisterJobReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RegisterWorker<WithCallbackMethod_RegisterJob<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RegisterWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RegisterWorker() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RegisterWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterWorker(::grpc::ServerContext* /*context*/, const ::RegisterWorkerRequest* /*request*/, ::RegisterWorkerReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RegisterJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RegisterJob() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RegisterJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterJob(::grpc::ServerContext* /*context*/, const ::RegisterJobRequest* /*request*/, ::RegisterJobReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RegisterWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RegisterWorker() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RegisterWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterWorker(::grpc::ServerContext* /*context*/, const ::RegisterWorkerRequest* /*request*/, ::RegisterWorkerReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterWorker(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RegisterJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RegisterJob() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_RegisterJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterJob(::grpc::ServerContext* /*context*/, const ::RegisterJobRequest* /*request*/, ::RegisterJobReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterJob(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RegisterWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RegisterWorker() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RegisterWorker(context, request, response); }));
    }
    ~WithRawCallbackMethod_RegisterWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterWorker(::grpc::ServerContext* /*context*/, const ::RegisterWorkerRequest* /*request*/, ::RegisterWorkerReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterWorker(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RegisterJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RegisterJob() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RegisterJob(context, request, response); }));
    }
    ~WithRawCallbackMethod_RegisterJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterJob(::grpc::ServerContext* /*context*/, const ::RegisterJobRequest* /*request*/, ::RegisterJobReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterJob(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RegisterWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RegisterWorker() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::RegisterWorkerRequest, ::RegisterWorkerReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::RegisterWorkerRequest, ::RegisterWorkerReply>* streamer) {
                       return this->StreamedRegisterWorker(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RegisterWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RegisterWorker(::grpc::ServerContext* /*context*/, const ::RegisterWorkerRequest* /*request*/, ::RegisterWorkerReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegisterWorker(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::RegisterWorkerRequest,::RegisterWorkerReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RegisterJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RegisterJob() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::RegisterJobRequest, ::RegisterJobReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::RegisterJobRequest, ::RegisterJobReply>* streamer) {
                       return this->StreamedRegisterJob(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RegisterJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RegisterJob(::grpc::ServerContext* /*context*/, const ::RegisterJobRequest* /*request*/, ::RegisterJobReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegisterJob(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::RegisterJobRequest,::RegisterJobReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RegisterWorker<WithStreamedUnaryMethod_RegisterJob<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RegisterWorker<WithStreamedUnaryMethod_RegisterJob<Service > > StreamedService;
};


#endif  // GRPC_master_5fservice_2eproto__INCLUDED
