// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: master_service.proto

#include "master_service.pb.h"
#include "master_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* MasterService_method_names[] = {
  "/MasterService/RegisterWorker",
  "/MasterService/RegisterJob",
};

std::unique_ptr< MasterService::Stub> MasterService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MasterService::Stub> stub(new MasterService::Stub(channel, options));
  return stub;
}

MasterService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RegisterWorker_(MasterService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RegisterJob_(MasterService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MasterService::Stub::RegisterWorker(::grpc::ClientContext* context, const ::RegisterWorkerRequest& request, ::RegisterWorkerReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::RegisterWorkerRequest, ::RegisterWorkerReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterWorker_, context, request, response);
}

void MasterService::Stub::async::RegisterWorker(::grpc::ClientContext* context, const ::RegisterWorkerRequest* request, ::RegisterWorkerReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::RegisterWorkerRequest, ::RegisterWorkerReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterWorker_, context, request, response, std::move(f));
}

void MasterService::Stub::async::RegisterWorker(::grpc::ClientContext* context, const ::RegisterWorkerRequest* request, ::RegisterWorkerReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterWorker_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::RegisterWorkerReply>* MasterService::Stub::PrepareAsyncRegisterWorkerRaw(::grpc::ClientContext* context, const ::RegisterWorkerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::RegisterWorkerReply, ::RegisterWorkerRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterWorker_, context, request);
}

::grpc::ClientAsyncResponseReader< ::RegisterWorkerReply>* MasterService::Stub::AsyncRegisterWorkerRaw(::grpc::ClientContext* context, const ::RegisterWorkerRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterWorkerRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MasterService::Stub::RegisterJob(::grpc::ClientContext* context, const ::RegisterJobRequest& request, ::RegisterJobReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::RegisterJobRequest, ::RegisterJobReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterJob_, context, request, response);
}

void MasterService::Stub::async::RegisterJob(::grpc::ClientContext* context, const ::RegisterJobRequest* request, ::RegisterJobReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::RegisterJobRequest, ::RegisterJobReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterJob_, context, request, response, std::move(f));
}

void MasterService::Stub::async::RegisterJob(::grpc::ClientContext* context, const ::RegisterJobRequest* request, ::RegisterJobReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterJob_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::RegisterJobReply>* MasterService::Stub::PrepareAsyncRegisterJobRaw(::grpc::ClientContext* context, const ::RegisterJobRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::RegisterJobReply, ::RegisterJobRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterJob_, context, request);
}

::grpc::ClientAsyncResponseReader< ::RegisterJobReply>* MasterService::Stub::AsyncRegisterJobRaw(::grpc::ClientContext* context, const ::RegisterJobRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterJobRaw(context, request, cq);
  result->StartCall();
  return result;
}

MasterService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MasterService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MasterService::Service, ::RegisterWorkerRequest, ::RegisterWorkerReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::RegisterWorkerRequest* req,
             ::RegisterWorkerReply* resp) {
               return service->RegisterWorker(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MasterService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MasterService::Service, ::RegisterJobRequest, ::RegisterJobReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::RegisterJobRequest* req,
             ::RegisterJobReply* resp) {
               return service->RegisterJob(ctx, req, resp);
             }, this)));
}

MasterService::Service::~Service() {
}

::grpc::Status MasterService::Service::RegisterWorker(::grpc::ServerContext* context, const ::RegisterWorkerRequest* request, ::RegisterWorkerReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MasterService::Service::RegisterJob(::grpc::ServerContext* context, const ::RegisterJobRequest* request, ::RegisterJobReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


